### ISSUE TITLE
TreeStyleTabs: I don't see the addon in the context menu

### ISSUE THREAD

**Issue by campbellkerr** [NiklasGollenstede/unload-tabs#14]
Am I doing something wrong? From the addon description you'd expect this to work by default. Thanks! 😀
![image](https://user-images.githubusercontent.com/38451588/38871034-f2927c80-4292-11e8-9d9a-95c91e9c7624.png)

**Comment by NiklasGollenstede** [comment]
I added a hint to the description that it needs to be enabled first (in the options on `about:addons`).
The reason is, that Tree Style Tabs must already be running when enabling the option, and re-connecting after extension restarts isn't entirely stable yet.
