### ISSUE TITLE
Is "tabs" permission really needed?

### ISSUE THREAD

**Issue by Lej77** [NiklasGollenstede/unload-tabs#15]
The `tabs` permission is only needed to access a tab's `url`, `title`, and `favIconUrl`. This information is available at the top of this article: [tabs - Mozilla | MDN](https://developer.mozilla.org/Add-ons/WebExtensions/API/tabs).

Is those properties really used by this extension? If not then you could remove the permission from your manifest without affecting the extension.

**Comment by NiklasGollenstede** [comment]
Thanks for your concern. While I generally agree that software should always work with as few privileges as possible, here are the reasons why I added the permission and intend to keep it at least for a while longer:

I did some experiments with the `favIconUrl`. I guess that is when I added the `tabs` permission.
You are probably right that the extension does not currently need the tabs permission, but the thing is, that while removing a permission is easy, I really dislike the current UX when one is added. There is no way for the extension(s author) to explain why the change is needed.
So before I remove that permission, I want to be sure that I won't need it in the future. And I actually expect I might. Besides, the `tabs` permission can sometimes make debugging a bit easier.

Also, I think that users who aren't quite that familiar with the WebExtension APIs won't think twice about a tab unloading extension that needs access to the tabs.

**Comment by Lej77** [comment]
@NiklasGollenstede Thanks for you detailed explanation. You are probably right in that it won't be an issue for most people so you might as well keep it. Alternatively you could make it an optional permission and allow the user to disable functionality that might require it, still that might not be worth the effort.
