### ISSUE TITLE
When closing a selected tab (A) next to an unloaded tab (B), B is briefly selected and gets the loading icon, before another tab (C) is correctly selected

### ISSUE THREAD

**Issue by lionelster** [NiklasGollenstede/unload-tabs#19]
B remains unloaded but retains the loading icon indefinitely, until manually selected and loaded.

Happens with the "Prevent Firefox from loading unloaded tabs" option enabled.

**Comment by NiklasGollenstede** [comment]
Sorry for the late reply.
This is a known Issue, mentioned on the post-installation page:

> Preventing tabs from loading doesn't always work completely. This is due to the way WebExtensions work. They report things (like the closing of a tab) asynchronously, that is, after it already happened. Sometimes (often randomly) that is too late. In these cases, UnloadTabs tries to revert the default actions, but that may not always work entirely:
>  *  Tabs may <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1450382">loose their icons</a> or <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1450371">display as loading</a>. These are Firefox bugs. Reloading the tab fixes the problem.
