### ISSUE TITLE
"Dim unloaded tabs" doesn’t work after browser restart

### ISSUE THREAD

**Issue by SimonSapin** [NiklasGollenstede/unload-tabs#22]
In Firefox 61.0.1, with Tree Style Tabs 2.4.24, and UnloadTabs 0.8.1, the "Dim unloaded tabs" checkbox works as expected at first. But after exiting and restarting the browser it loses its effect until I go back into the extension preferences to uncheck the checkbox and check it again.

**Comment by NiklasGollenstede** [comment]
I updated the release version to 0.8.2. I hope that has the problem already solved.

**Comment by SimonSapin** [comment]
Yes, it looks like this is fixed in 0.8.2. Thanks!
