### ISSUE TITLE
When unloading all tabs in a tabgroup, firefox will jump into a random tabgroup

### ISSUE THREAD

**Issue by char101** [NiklasGollenstede/unload-tabs#4]
Hi,

I think `findClosestNonPending` should only search tabs in the [`visibleTabs`](https://developer.mozilla.org/en-US/docs/XUL/Property/visibleTabs) list, and if no loaded tab is found, it should just return null. Then we can change this into

```javascript
gBrowser.selectedTab = findClosestNonPending(tab.parentNode.children, tab) || 
                       gBrowser.addTab();
```

Because otherwise the browser will jump into a random tabgroup which is a bit confusing.

**Comment by NiklasGollenstede** [comment]
Yes, that seems much smoother.
