### ISSUE TITLE
Feature Request: Stand out unloaded tabs

### ISSUE THREAD

**Issue by nadapez** [NiklasGollenstede/unload-tabs#43]
1. It would be nice to show in tab bar which are unloaded by changing the color of the tab

**Comment by NiklasGollenstede** [comment]
Doing that from an extension used to be pretty much impossible (not sure whether that ever changed).

There is a small CSS-snippet in https://github.com/NiklasGollenstede/unload-tabs/blob/master/dim-unloaded-tabs.css that can be added to the `chrome/user.chrome.css`. (Googling `user.chrome.css` will give you better instructions than I could type here. If in doubt, at the while content of the file.)

**Comment by NiklasGollenstede** [comment]
Also, sorry for not replying earlier, must have forgotten ...
