### ISSUE TITLE
A mnemonic would be nice

### ISSUE THREAD

**Issue by chris-morgan** [NiklasGollenstede/unload-tabs#7]
“Unload Tab” and “Unload Other Tabs” have no mnemonic. All the standard Firefox items do<sup>†</sup>, and I’d say that in general everything should. This makes batch unloading quite slow to accomplish.

U is taken by “**U**ndo close tab”. I’m thinking L, in “Un**l**oad Tab”, or X, i.e. “Unload Tab (**X**)” (I think some platforms hide the “ (**X**)” part somehow? Like with “Inspect Element (**Q**)”?).

I’m not so fussed about Unload Other Tabs. You’ll only ever use it once at a time.

----

<sup>†</sup> *OK, except for “Open in new non-e10s window” if you’re on Nightly.*

**Comment by NiklasGollenstede** [comment]
I agree and will look into it. In the meantime you can unload selective groups of tabs in combination with https://addons.mozilla.org/addon/multiple-tab-handler.

But where I live we celebrate Christmas on the 24th, and I intend to do that first :)
Mery Christmas!
