### ISSUE TITLE
Tab Tree problem

### ISSUE THREAD

**Issue by megumn** [NiklasGollenstede/unload-tabs#9]
In Tab Tree "Unload Tab (X)" doesn’t unload tab, but create new tab.

**Comment by NiklasGollenstede** [comment]
"Tab Tree" with Tree Style Tab? "create new tab" duplicate the old one? Is it loaded/unloaded? Where is it added? Are there any related error messaged (`Ctrl`+`Shift`+`J `)?

Anyway. I don't think I'll find time to work on this for the next few weeks.

**Comment by megumn** [comment]
> "Tab Tree" with Tree Style Tab?
Only Tab Tree addon. In Tree Style Tab all work.

> "create new tab" duplicate the old one?
No, creates new purge white tab. Old tab has no changes, it is not unloaded.

> Where is it added?
A New tab is added in the end of the tree

>  Are there any related error messaged
`17:46:05.891 NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "browser is undefined" {file: "resource://app/modules/sessionstore/TabState.jsm" line: 100}]'[JavaScript Error: "browser is undefined" {file: "resource://app/modules/sessionstore/TabState.jsm" line: 100}]' when calling method: [nsISessionStore::getTabState] 1 main.js:131
`

**Comment by NiklasGollenstede** [comment]
Thanks. That should help to track the bug down once I have time for that.

**Comment by NiklasGollenstede** [comment]
I'm sorry that I never worked on this, but now the version of UnloadTabs that was affected by this isn't supported by Firefox anymore.

Feel free to check out the [new beta version](https://github.com/NiklasGollenstede/unload-tabs/releases/tag/v0.8.0b3) though. That should be compatible with pretty much all other extensions.
